name: Responsive Images (verify)
on:
  workflow_dispatch:
  pull_request:
    paths:
      - 'assets/images/**'
      - 'tools/responsive-images.js'
      - 'package.json'
      - 'package-lock.json'
  push:
    paths:
      - 'assets/images/**'
      - 'tools/responsive-images.js'
      - 'package.json'
      - 'package-lock.json'

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - run: npm ci --no-audit --no-fund

      # 👇 Aquí forzamos la recompilación de sharp en linux
      - name: Rebuild sharp for linux
        run: npm install --include=optional sharp

      - name: Generate responsive images
        run: npm run responsive

      - name: Ensure no generated changes
        run: git diff --exit-code

